<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>commons-learn</artifactId>
    <version>1.0-SNAPSHOT</version>
    <modules>
        <module>commons-lang</module>
        <module>commons-lang3</module>
        <module>commons-io</module>
        <module>commons-collection</module>
        <module>commons-configuration</module>
        <module>commons-text</module>
        <module>commons-pool2</module>
        <module>commons-vfs2</module>
    </modules>
    <packaging>pom</packaging>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <junit.version>4.11</junit.version>

        <commons.lang.version>2.6</commons.lang.version>
        <commons.lang3.version>3.12.0</commons.lang3.version>
        <commons.collections.version>4.4</commons.collections.version>
        <commons.io.version>2.13.0</commons.io.version>
        <commons.configuration2.version>2.9.0</commons.configuration2.version>
        <commons.text.version>1.10.0</commons.text.version>
        <commons.pool2.version>2.11.1</commons.pool2.version>
        <commons.vfs2.version>2.9.0</commons.vfs2.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- test -->
            <dependency>
                <groupId>junit</groupId>
                <artifactId>junit</artifactId>
                <version>${junit.version}</version>
            </dependency>

            <dependency>
                <groupId>commons-lang</groupId>
                <artifactId>commons-lang</artifactId>
                <version>${commons.lang.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
                <version>${commons.lang3.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-collections4</artifactId>
                <version>${commons.collections.version}</version>
            </dependency>
            <dependency>
                <groupId>commons-io</groupId>
                <artifactId>commons-io</artifactId>
                <version>${commons.io.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-configuration2</artifactId>
                <version>${commons.configuration2.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-text</artifactId>
                <version>${commons.text.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-pool2</artifactId>
                <version>${commons.pool2.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-vfs2</artifactId>
                <version>${commons.vfs2.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>